### ISSUE TITLE
Pool info: "Statically configured" missing unit suffix "M" (dCache 4.2.26)

### ISSUE THREAD

**Issue by onnozweers** [dCache/dcache#4700]
Dear dCache devs,

I have this pool:

```
--- rep (Repository manager) ---
State : OPEN
Files : 26925
Disk space
    Total    : 17476267M
    Used     : 15234678958742    [0.8313515719144687]
    Free     : 3090515187050    Gap : 10737418240
    Precious : 0    [0.0]
    Removable: 0    [0.0]
File system
    Size : 415464142405632
    Free : 164698030993408    [0.3964193637500673]
Limits for maximum disk space
    File system          : 179932709952150
    Statically configured: 17476267
    Runtime configured   : 18325194145792
```

The line `Statically configured: 17476267` is missing an `M`. Just to be sure, I set the size again to what should the the correct value:

`set max diskspace 17476267M`

Then `save`. But the output does not change. Any idea what could be wrong?

Kind regards,
Onno

**Comment by onnozweers** [comment]
I checked whether the value comes from the setup file. This is from the setup file:

    set max diskspace 17476267M

**Comment by kofemann** [comment]
Quite an old issue, but anyway....
The `Statically configured` reports the value which is configured in the layout file,
for example:

```
[dCacheDomain/pool]
pool.name=pool_read
pool.size=100M
```

I would assume that the `M` suffix is missing there (or the issue is fixed without being updated in github).

**Comment by onnozweers** [comment]
Hi Tigran, thanks for explaining. This is indeed a very old issue. I don't think the pool with this issue still exists. So I will close this ticket.
