### ISSUE TITLE
NFS: dot commands fail on files containing brackets

### ISSUE THREAD

**Issue by DmitryLitvintsev** [dCache/dcache#5547]
[root@fndca3b ~]# ls -al /pnfs/fnal.gov/usr/damic/raw/connie/2015_extra/noiseScans/noiseScan-cryoOFF/29Sep15_1622_CRYOunplugged/pixelStats_[4270:4330,10:40].txt
-rw-rw-r-- 1 47002 9932 728 Sep 29  2015 /pnfs/fnal.gov/usr/damic/raw/connie/2015_extra/noiseScans/noiseScan-cryoOFF/29Sep15_1622_CRYOunplugged/pixelStats_[4270:4330,10:40].txt

[root@fndca3b ~]# cat  /pnfs/fnal.gov/usr/damic/raw/connie/2015_extra/noiseScans/noiseScan-cryoOFF/29Sep15_1622_CRYOunplugged/".(id)(pixelStats_[4270:4330,10:40].txt)"
cat: /pnfs/fnal.gov/usr/damic/raw/connie/2015_extra/noiseScans/noiseScan-cryoOFF/29Sep15_1622_CRYOunplugged/.(id)(pixelStats_[4270:4330,10:40].txt): No such file or directory

**Comment by kofemann** [comment]
I think the issue is fixed in https://github.com/dCache/dcache/commit/1dee55f9847c7221b791b228007aadb24d4cde1e, but we need a proof before issue can be closed.

**Comment by DmitryLitvintsev** [comment]
Still fails on level 4:

```
[root@fdm1808 ~]# cat /pnfs/fnal.gov/usr/damic/raw/connie/2015_extra/noiseScans/noiseScan-cryoOFF/29Sep15_1622_CRYOunplugged/".(use)(4)(pixelStats_[4270:4330,10:40].txt)"
cat: /pnfs/fnal.gov/usr/damic/raw/connie/2015_extra/noiseScans/noiseScan-cryoOFF/29Sep15_1622_CRYOunplugged/.(use)(4)(pixelStats_[4270:4330,10:40].txt): No such file or directory
````

layer 4 exists

```
chimera=# select  * from t_level_4 where inumber = 1240431145;
  inumber   | imode | inlink | iuid  | igid | isize |         ictime          |         iatime          |         imtime          |                
                                                                                                                                                   
                            ifiledata                                                                                                              
                                                                                 
------------+-------+--------+-------+------+-------+-------------------------+-------------------------+-------------------------+----------------
---------------------------------------------------------------------------------------------------------------------------------------------------
---------------------------------------------------------------------------------------------------------------------------------------------------
---------------------------------------------------------------------------------
 1240431145 | 33204 |      1 | 47002 | 9932 |   356 | 2020-09-16 22:37:53.692 | 2018-03-16 17:18:17.594 | 2020-09-16 22:37:53.692 | pagg04:damic.da
mic-MIGRATION.cpio_odc\012/volumes/aggwrite/cache/d4c/264/00005C222B4713CF44A98245579ED9264395\012728\012damic\012/pnfs/fnal.gov/usr/damic/raw/conn
ie/2015_extra/noiseScans/noiseScan-cryoOFF/29Sep15_1622_CRYOunplugged/pixelStats_[4270:4330,10:40].txt\012\01200006F3EB6135AAC44288EB3BF17C533B157\
012\012CDMS160031387300002\012pagg04:/volumes/aggwrite/cache:0\0122538789645\012
(1 row)
```

Success on layer 1:

```
[root@fdm1808 ~]# cat /pnfs/fnal.gov/usr/damic/raw/connie/2015_extra/noiseScans/noiseScan-cryoOFF/29Sep15_1622_CRYOunplugged/".(use)(1)(pixelStats_[4270:4330,10:40].txt)"
CDMS160031387300002
```

**Comment by DmitryLitvintsev** [comment]
let me double check ...... it works on some hosts... )

**Comment by kofemann** [comment]
fixed in 6.0
